### ISSUE TITLE
fb app not configured properly

### ISSUE THREAD

**Issue by kylemac** [carrot/parm-genie#2]
might be sandboxed so only your account can work. or bad configu values. 

happens on click of "log in with facebook"

![](https://i.cloudup.com/U_wpm7lAcj-3000x3000.png)

**Comment by nporteschaikin** [comment]
@kylemac are you accessing this via parm.bycarrot.com?

**Comment by jescalan** [comment]
I got the same error accessing through parm.bycarrot.com

**Comment by kylemac** [comment]
yup, this is happening locally and on http://parm.bycarrot.com

**Comment by kylemac** [comment]
I should also note that this has never worked for me - same error - I was waiting for you to be complete before I let you know.

**Comment by nporteschaikin** [comment]
@kylemac @jenius whoops.

![image](https://cloud.githubusercontent.com/assets/1634280/3046420/c37e99b2-e128-11e3-8902-aa079a0bd609.png)

Give it a spin now.
