### ISSUE TITLE
[discussion] Pattern

### ISSUE THREAD

**Issue by nporteschaikin** [carrot/parm-genie#3]
What do y'all think of this approach/pattern for writing PARM apps?  Before we commit to a PARM [sprout](https://github.com/carrot/sprout) template (or PARM in general), I want your feedback.  Some of my concerns and questions with this pattern:
- Too much requiring (although @jenius and I agreed that SPAs should cache as much as possible on load).
- The "nested" requiring of controllers in `app.coffee` is anti-pattern.
- Do controllers complicate the interaction between models and views/what are the benefits of strict MVC for a Backbone.js/Marionette app?

Pose questions, provide opinions, etc. please!

**Comment by jescalan** [comment]
Yeah this is a good discussion to have, would love to have @kylemac, @joshrowley, and @pruett involved at very least.

So as for the require stuff, I think we can use the require optimizer to squish things if we need, which is good. We also could try going all out with a browserify approach, which @pruett and I have experimented with a bit ([globtester](https://github.com/carrot/globtester) is built with browserify and roots), but browserify has very poor support for coffeescript, which is a bummer. We would however have to build r.js into a roots extension, which really shouldnt be that bad but is more than zero work.

The nested requiring I'm really not about. I think we're going pretty hard against [yagni](http://en.wikipedia.org/wiki/You_aren't_gonna_need_it) and against the nature of node-style explicit loading by including that piece. I feel like our base template should include just one controller, and if you need to add more, you can do so as the app requires, and explicitly load them in where you need. Things are not only less messy and faster, but more clear that way.

Controllers are definitely necessary though in my opinion. Neither models nor views should be responsible for reacting to routes and/or deciding which view to show and where, so the responsibility for that falls with controllers.

**Comment by kylemac** [comment]
sunsetting this project.
