### ISSUE TITLE
get rid of # in url

### ISSUE THREAD

**Issue by kylemac** [carrot/parm-genie#7]
get into this new [charge](https://github.com/carrot/charge) thing we've got going on and use the `"routes": { "**": "/index.html" }` option to get your SPA on.

**Comment by nporteschaikin** [comment]
@kylemac wait for [this pr](https://github.com/jenius/roots/pull/471) to be merged in?

**Comment by jescalan** [comment]
Yeah once this guy is merged and tests are implemented there will be another roots prerelease, then it would be a good time for it. Although you should already be able to use charge in production at least with the heroku buildpack kyle made, if he has it integrated.

**Comment by kylemac** [comment]
that will certainly help your local development flow, since it'll be built right into roots so feel free to wait. but since you're using the buildpack, the `charge.json` compatibility is already baked in. If you wanted to run it locally, next to a roots watch, I've done this. 

```
$ npm i charge -g
$ roots watch --no-open
# new terminal tab
$ cd public; charge -p 1112
$ open http://localhost:1112
```

**Comment by jescalan** [comment]
Ah nice call with that snippet :point_up: - if all goes smoothly with the tests I'm aiming to have the prerelease out by the end of this week :tada:

**Comment by nporteschaikin** [comment]
@jenius @kylemac thanks! will implement on heroku now.
